language: node_js
node_js:
  - "14"
script:
  - cd chinese-ocr-webapp
  - npm install
  - npm install -g firebase-tools
  - npm install -g @vue/cli
  - npm run twbuild
  - npm run lint
  - npm run build
after_success:
  - firebase deploy --project chinese-ocr-274418 --token $FIREBASE_TOKEN